name: ci

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform:
        - os: ubuntu-latest
          shell: bash
        - os: macos-latest
          shell: bash
      fail-fast: false

    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm test